from enum import Enum


GENERATE_UNDIRECTED_GRAPHS = False
UNDIRECTED_PREFIX = "undir_"

# "fast" - very fast mode (only small graphs),
# "medium" - medium (small-sized and medium-sized graphs)
# "full" - full (test on all available graphs)
# "one_large" - one large graph per category,
# "rating" - rating mode

print_timings = True

#"cc": [ ["-cv"], ["-bfs-based"] ],
# "sssp": [ ["-push", "-all-active"], ["-pull", "-all-active"] ],

benchmark_args = {"bfs": [ ["-top-down"]],
                  "sssp": [ ["-push", "-all-active"]],
                  "pr": [ ["-pull"] ],
                  "cc": [ ["-cv"] ],
                  "sswp": [ ["-push"] ],
                  "rw": [ ["-it", "100", "-wv", "20"] ],
                  "hits": [ [] ],
                  "scc": [ [] ],
                  "coloring": [ [] ],
                  "tc": [ ["-bfs-based", "-it", "500"], ["-purdoms", "-it", "500"] ],
                  "mf": [ [] ]}


available_formats = ["csr", "csr_vg", "vcsr", "el", "el_csr_based", "el_2D_seg"]


def requires_undir_graphs(app_name):
    if not GENERATE_UNDIRECTED_GRAPHS:
        return False
    if app_name in ["cc", "coloring"]:
        return True
    return False


common_iterations = 10
perf_pattern = "AVG_PERF"
correctness_pattern = "error count:"

GRAPHS_DIR = "./bin/input_graphs/"
SOURCE_GRAPH_DIR = "./bin/source_graphs/"


# how to add new graph with new category
# 1. add link (http://konect.cc/networks/amazon/ for example) to both dicts
# 2.

all_konect_graphs_data = {
    'soc_catster': {'link': 'petster-friendships-cat'},
    'soc_libimseti': {'link': 'libimseti'},
    'soc_dogster': {'link': 'petster-friendships-dog'},
    'soc_catster_dogster': {'link': 'petster-carnivore'},
    'soc_youtube_friendships': {'link': 'com-youtube'},
    'soc_pokec': {'link': 'soc-pokec-relationships'},
    'soc_orkut': {'link': 'orkut-links'},
    'soc_livejournal': {'link': 'soc-LiveJournal1'},
    'soc_livejournal_links': {'link': 'livejournal-links'},
    'soc_twitter_www': {'link': 'twitter'},
    'soc_friendster': {'link': 'friendster'},

    'web_stanford': {'link': 'web-Stanford'},
    'web_baidu_internal': {'link': 'zhishi-baidu-internallink'},
    'web_wikipedia_links_fr': {'link': 'wikipedia_link_fr'},
    'web_wikipedia_links_ru': {'link': 'wikipedia_link_ru'},
    'web_zhishi': {'link': 'zhishi-all'},
    'web_wikipedia_links_en': {'link': 'wikipedia_link_en'},
    'web_dbpedia_links': {'link': 'dbpedia-link'},
    'web_uk_domain_2002': {'link': 'dimacs10-uk-2002'},
    'web_web_trackers': {'link': 'trackers-trackers', 'unarch_graph_name': 'trackers'},

    'road_colorado': {'link': 'dimacs9-COL'},
    'road_texas': {'link': 'roadNet-TX'},
    'road_california': {'link': 'roadNet-CA'},
    'road_eastern_usa': {'link': 'dimacs9-E'},
    'road_western_usa': {'link': 'dimacs9-W'},
    'road_central_usa': {'link': 'dimacs9-CTR'},
    'road_full_usa': {'link': 'dimacs9-USA'},

    'rating_epinions': {'link': 'epinions-rating'},
    'rating_amazon_ratings': {'link': 'amazon-ratings'},
    'rating_yahoo_songs': {'link': 'yahoo-song'}
}

great_graphs_data = {
    'DBpedia countries': {'link': 'dbpedia-country'},
    'Teams': {'link': 'dbpedia-team'},
    'Actor movies': {'link': 'actor-movie'},
    'IMDB': {'link': 'actor2'},
    'Flickr': {'link': 'flickr-growth'},
    'CiteSeer': {'link': 'citeseer'},
    'Wikinews edits (es)': {'link': 'edit-eswikinews'},
    'Wikipedia edits (su)': {'link': 'edit-suwiki'},
    'Wiktionary edits (sa)': {'link': 'edit-sawiktionary'},
    'Wikipedia edits (ia)': {'link': 'edit-iawiki'},
    'Wikipedia edits (vec)': {'link': 'edit-vecwiki'},
    'Wiktionary edits (ml)': {'link': 'edit-mlwiktionary'},
    'Wikibooks edits (de)': {'link': 'edit-dewikibooks'},
    'Wikipedia edits (nap)': {'link': 'edit-napwiki'},
    'Wikiversity edits (fr)': {'link': 'edit-frwikiversity'},
    'Wikipedia edits (ne)': {'link': 'edit-newiki'},
    'Wikipedia edits (bar)': {'link': 'edit-barwiki'},
    'Wikipedia edits (cv)': {'link': 'edit-cvwiki'},
    'Wiktionary edits (li)': {'link': 'edit-liwiktionary'},
    'Wikipedia edits (ku)': {'link': 'edit-kuwiki'},
    'Wiktionary edits (gl)': {'link': 'edit-glwiktionary'},
    'Wikipedia edits (qu)': {'link': 'edit-quwiki'},
    'Wiktionary edits (kn)': {'link': 'edit-knwiktionary'},
    'Wiktionary edits (ar)': {'link': 'edit-arwiktionary'},
    'Wikipedia edits (scn)': {'link': 'edit-scnwiki'},
    'Wikipedia edits (ht)': {'link': 'edit-htwiki'},
    'Wikipedia edits (als)': {'link': 'edit-alswiki'},
    'Wikipedia edits (lmo)': {'link': 'edit-lmowiki'},
    'Wikipedia edits (ba)': {'link': 'edit-bawiki'},
    'Wikipedia edits (arz)': {'link': 'edit-arzwiki'},
    'Wikiquote edits (it)': {'link': 'edit-itwikisource'},
    'Wikinews edits (de)': {'link': 'edit-dewikinews'},
    'Wiktionary edits (fa)': {'link': 'edit-fawiktionary'},
    'Wikipedia edits (nds)': {'link': 'edit-ndswiki'},
    'Wikinews edits (fr)': {'link': 'edit-frwikinews'},
    'Wikipedia edits (bpy)': {'link': 'edit-bpywiki'},
    'Wikipedia edits (mg)': {'link': 'edit-mgwiki'},
    'Wikipedia edits (kn)': {'link': 'edit-knwiki'},
    'Wiktionary edits (my)': {'link': 'edit-mywiktionary'},
    'Wikiquote edits (he)': {'link': 'edit-hewikisource'},
    'Wikipedia edits (ga)': {'link': 'edit-gawiki'},
    'Wiktionary edits (chr)': {'link': 'edit-chrwiktionary'},
    'Wikiquote edits (es)': {'link': 'edit-eswikisource'},
    'Wikiquote edits (bn)': {'link': 'edit-bnwikisource'},
    'Wikipedia edits (tg)': {'link': 'edit-tgwiki'},
    'Wikipedia edits (new)': {'link': 'edit-newwiki'},
    'Wikipedia edits (pms)': {'link': 'edit-pmswiki'},
    'Wiktionary edits (cs)': {'link': 'edit-cswiktionary'},
    'Wikipedia edits (io)': {'link': 'edit-iowiki'},
    'Wikivoyage edits (de)': {'link': 'edit-dewikivoyage'},
    'Wiktionary edits (id)': {'link': 'edit-idwiktionary'},
    'Wiktionary edits (th)': {'link': 'edit-thwiktionary'},
    'Wiktionary edits (ro)': {'link': 'edit-rowiktionary'},
    'Wiktionary edits (te)': {'link': 'edit-tewiktionary'},
    'Wikipedia edits (zh-yue)': {'link': 'edit-zh_yuewiki'},
    'Wikipedia edits (sw)': {'link': 'edit-swwiki'},
    'Wiktionary edits (ja)': {'link': 'edit-jawiktionary'},
    'Wikinews edits (it)': {'link': 'edit-itwikinews'},
    'Wikipedia edits (ast)': {'link': 'edit-astwiki'},
    'Wiktionary edits (et)': {'link': 'edit-etwiktionary'},
    'Wiktionary edits (no)': {'link': 'edit-nowiktionary'},
    'Wiktionary edits (bg)': {'link': 'edit-bgwiktionary'},
    'Wikiquote edits (zh)': {'link': 'edit-zhwikisource'},
    'Wiktionary edits (ca)': {'link': 'edit-cawiktionary'},
    'Wikipedia edits (jv)': {'link': 'edit-jvwiki'},
    'Wiktionary edits (hy)': {'link': 'edit-hywiktionary'},
    'Wikiquote edits (en)': {'link': 'edit-enwikisource'},
    'Wikipedia edits (is)': {'link': 'edit-iswiki'},
    'Wikipedia edits (tl)': {'link': 'edit-tlwiki'},
    'Wikipedia edits (mr)': {'link': 'edit-mrwiki'},
    'Wikipedia edits (af)': {'link': 'edit-afwiki'},
    'Wikipedia edits (an)': {'link': 'edit-anwiki'},
    'Wiktionary edits (sh)': {'link': 'edit-shwiktionary'},
    'Wikiversity edits (en)': {'link': 'edit-enwikiversity'},
    'Wikiquote edits (pl)': {'link': 'edit-plwikisource'},
    'Wikipedia edits (sq)': {'link': 'edit-sqwiki'},
    'Wikipedia edits (min)': {'link': 'edit-minwiki'},
    'Wiktionary edits (ta)': {'link': 'edit-tawiktionary'},
    'Wikipedia edits (br)': {'link': 'edit-brwiki'},
    'Wiktionary edits (lt)': {'link': 'edit-ltwiktionary'},
    'Wikipedia edits (ce)': {'link': 'edit-cewiki'},
    'Wikipedia edits (be-x-old)': {'link': 'edit-be_x_oldwiki'},
    'Wikipedia edits (zh-min-nan)': {'link': 'edit-zh_min_nanwiki'},
    'Wikipedia edits (lb)': {'link': 'edit-lbwiki'},
    'Wikipedia edits (uz)': {'link': 'edit-uzwiki'},
    'Wikipedia edits (oc)': {'link': 'edit-ocwiki'},
    'Wiktionary edits (tr)': {'link': 'edit-trwiktionary'},
    'Wikipedia edits (tt)': {'link': 'edit-ttwiki'},
    'Wiktionary edits (vi)': {'link': 'edit-viwiktionary'},
    'Wikipedia edits (te)': {'link': 'edit-tewiki'},
    'Wiktionary edits (ku)': {'link': 'edit-kuwiktionary'},
    'Wiktionary edits (hu)': {'link': 'edit-huwiktionary'},
    'Wiktionary edits (pt)': {'link': 'edit-ptwiktionary'},
    'Wikipedia edits (ta)': {'link': 'edit-tawiki'},
    'Wikivoyage edits (en)': {'link': 'edit-enwikivoyage'},
    'Wikipedia edits (bs)': {'link': 'edit-bswiki'},
    'Wikipedia edits (kk)': {'link': 'edit-kkwiki'},
    'Wikibooks edits (en)': {'link': 'edit-enwikibooks'},
    'Wikipedia edits (ml)': {'link': 'edit-mlwiki'},
    'Wikipedia edits (be)': {'link': 'edit-bewiki'},
    'Wiktionary edits (io)': {'link': 'edit-iowiktionary'},
    'Wikipedia edits (lv)': {'link': 'edit-lvwiki'},
    'Wikipedia edits (bn)': {'link': 'edit-bnwiki'},
    'Wikiquote edits (ru)': {'link': 'edit-ruwikisource'},
    'Wikipedia edits (ur)': {'link': 'edit-urwiki'},
    'Wikipedia edits (mk)': {'link': 'edit-mkwiki'},
    'Wiktionary edits (sv)': {'link': 'edit-svwiktionary'},
    'Wikipedia edits (cy)': {'link': 'edit-cywiki'},
    'Wikipedia edits (nn)': {'link': 'edit-nnwiki'},
    'Wikipedia edits (la)': {'link': 'edit-lawiki'},
    'Wikiquote edits (de)': {'link': 'edit-dewikisource'},
    'Wikipedia edits (hi)': {'link': 'edit-hiwiki'},
    'Wiktionary edits (it)': {'link': 'edit-itwiktionary'},
    'Wiktionary edits (fi)': {'link': 'edit-fiwiktionary'},
    'Wikipedia edits (vo)': {'link': 'edit-vowiki'},
    'Wikipedia edits (ka)': {'link': 'edit-kawiki'},
    'Wikinews edits (sr)': {'link': 'edit-srwikinews'},
    'Wikipedia edits (az)': {'link': 'edit-azwiki'},
    'Wiktionary edits (ko)': {'link': 'edit-kowiktionary'},
    'Wiktionary edits (nl)': {'link': 'edit-nlwiktionary'},
    'Wikipedia edits (ms)': {'link': 'edit-mswiki'},
    'Wiktionary edits (el)': {'link': 'edit-elwiktionary'},
    'Wikipedia edits (gl)': {'link': 'edit-glwiki'},
    'Wikipedia edits (et)': {'link': 'edit-etwiki'},
    'Wikipedia edits (hr)': {'link': 'edit-hrwiki'},
    'Wikipedia edits (sl)': {'link': 'edit-slwiki'},
    'Wikinews edits (en)': {'link': 'edit-enwikinews'},
    'Wikipedia edits (lt)': {'link': 'edit-ltwiki'},
    'Wiktionary edits (es)': {'link': 'edit-eswiktionary'},
    'Wikipedia edits (simple)': {'link': 'edit-simplewiki'},
    'Wikipedia edits (hy)': {'link': 'edit-hywiki'},
    'Wiktionary edits (zh)': {'link': 'edit-zhwiktionary'},
    'Wikipedia edits (el)': {'link': 'edit-elwiki'},
    'Wikipedia edits (th)': {'link': 'edit-thwiki'},
    'Wikipedia edits (eu)': {'link': 'edit-euwiki'},
    'Wiktionary edits (pl)': {'link': 'edit-plwiktionary'},
    'Wiktionary edits (de)': {'link': 'edit-dewiktionary'},
    'Wikipedia edits (sk)': {'link': 'edit-skwiki'},
    'Wikipedia edits (eo)': {'link': 'edit-eowiki'},
    'Wikipedia edits (war)': {'link': 'edit-warwiki'},
    'Wikipedia edits (bg)': {'link': 'edit-bgwiki'},
    'Wikiquote edits (fr)': {'link': 'edit-frwikisource'},
    'Wikipedia edits (da)': {'link': 'edit-dawiki'},
    'Wiktionary edits (ru)': {'link': 'edit-ruwiktionary'},
    'DBLP': {'link': 'dblp_coauthor'},
    'Wikipedia edits (ro)': {'link': 'edit-rowiki'},
    'Wikipedia edits (id)': {'link': 'edit-idwiki'},
    'Wikipedia edits (cs)': {'link': 'edit-cswiki'},
    'Wikipedia edits (sr)': {'link': 'edit-srwiki'},
    'Wikipedia edits (fi)': {'link': 'edit-fiwiki'},
    'Wikipedia edits (tr)': {'link': 'edit-trwiki'},
    'Wikipedia edits (ko)': {'link': 'edit-kowiki'},
    'Wikipedia edits (no)': {'link': 'edit-nowiki'},
    'Wikipedia edits (ceb)': {'link': 'edit-cebwiki'},
    'Wikipedia edits (ca)': {'link': 'edit-cawiki'},
    'Wikipedia edits (hu)': {'link': 'edit-huwiki'},
    'Wikipedia edits (he)': {'link': 'edit-hewiki'},
    'Wikipedia edits (fa)': {'link': 'edit-fawiki'},
    'Wikipedia edits (uk)': {'link': 'edit-ukwiki'},
    'Wikipedia edits (ar)': {'link': 'edit-arwiki'},
    'Wiktionary edits (mg)': {'link': 'edit-mgwiktionary'},
    'Wiktionary edits (fr)': {'link': 'edit-frwiktionary'},
    'Wikipedia edits (vi)': {'link': 'edit-viwiki'},
    'Wikipedia edits (pt)': {'link': 'edit-ptwiki'},
    'Wikipedia edits (sv)': {'link': 'edit-svwiki'},
    'Wikipedia edits (zh)': {'link': 'edit-zhwiki'},
    'Wikipedia edits (sh)': {'link': 'edit-shwiki'},
    'Wikipedia edits (pl)': {'link': 'edit-plwiki'},
    'Wikipedia edits (nl)': {'link': 'edit-nlwiki'},
    'Wikipedia edits (ja)': {'link': 'edit-jawiki'},
    'Wiktionary edits (en)': {'link': 'edit-enwiktionary'},
    'Wikipedia edits (ru)': {'link': 'edit-ruwiki'},
    'US patents': {'link': 'patentcite'},
    'DBLP co-authorship': {'link': 'com-dblp'},
    'arXiv hep-th': {'link': 'ca-cit-HepTh'},
    'arXiv hep-ph': {'link': 'ca-cit-HepPh'},
    'Wikipedia talk (sv)': {'link': 'wiki_talk_sv'},
    'Wikipedia talk (vi)': {'link': 'wiki_talk_vi'},
    'Facebook': {'link': 'facebook-wosn-wall'},
    'Linux kernel mailing list replies': {'link': 'lkml-reply'},
    'Wikipedia talk (ja)': {'link': 'wiki_talk_ja'},
    'Enron': {'link': 'enron'},
    'Wikipedia talk (pl)': {'link': 'wiki_talk_pl'},
    'Wikipedia talk (nl)': {'link': 'wiki_talk_nl'},
    'Wikipedia talk (ar)': {'link': 'wiki_talk_ar'},
    'Wikipedia talk (ru)': {'link': 'wiki_talk_ru'},
    'Wikipedia talk (pt)': {'link': 'wiki_talk_pt'},
    'Wikipedia threads (de)': {'link': 'wikipedia-discussions-de'},
    'Wikipedia talk (zh)': {'link': 'wiki_talk_zh'},
    'Wikipedia talk (es)': {'link': 'wiki_talk_es'},
    'Wikipedia messages (en)': {'link': 'wiki-Talk'},
    'Wikipedia talk (it)': {'link': 'wiki_talk_it'},
    'Wikipedia talk (fr)': {'link': 'wiki_talk_fr'},
    'Wikipedia talk (de)': {'link': 'wiki_talk_de'},
    'Wikipedia talk (en)': {'link': 'wiki_talk_en'},
    'Skitter': {'link': 'as-skitter'},
    'vi.sualize.us tag–item': {'link': 'pics_ti'},
    'TV Tropes': {'link': 'dbtropes-feature'},
    'Wikipedia categories (en)': {'link': 'wiki-en-cat'},
    'BibSonomy tag–item': {'link': 'bibsonomy-2ti'},
    'CiteULike tag–item': {'link': 'citeulike-ti'},
    'Reality Mining': {'link': 'mit'},
    'Wikipedia links (arz)': {'link': 'wikipedia_link_arz'},
    'Wikipedia links (pa)': {'link': 'wikipedia_link_pa'},
    'Wikipedia links (nds)': {'link': 'wikipedia_link_nds'},
    'Wikipedia links (ps)': {'link': 'wikipedia_link_ps'},
    'Wikipedia links (pms)': {'link': 'wikipedia_link_pms'},
    'Wikipedia links (yi)': {'link': 'wikipedia_link_yi'},
    'Wikipedia links (bar)': {'link': 'wikipedia_link_bar'},
    'Wikipedia links (als)': {'link': 'wikipedia_link_als'},
    'Wikipedia links (io)': {'link': 'wikipedia_link_io'},
    'Wikipedia links (ku)': {'link': 'wikipedia_link_ku'},
    'Wikipedia links (min)': {'link': 'wikipedia_link_min'},
    'Wikipedia links (vo)': {'link': 'wikipedia_link_vo'},
    'Wikipedia links (cv)': {'link': 'wikipedia_link_cv'},
    'Wikipedia links (ky)': {'link': 'wikipedia_link_ky'},
    'Wikipedia links (nap)': {'link': 'wikipedia_link_nap'},
    'Wikipedia links (roa-tara)': {'link': 'wikipedia_link_roa_tara'},
    'Wikipedia links (yo)': {'link': 'wikipedia_link_yo'},
    'Wikipedia links (fy)': {'link': 'wikipedia_link_fy'},
    'Wikipedia links (ckb)': {'link': 'wikipedia_link_ckb'},
    'Wikipedia links (sw)': {'link': 'wikipedia_link_sw'},
    'Wikipedia links (is)': {'link': 'wikipedia_link_is'},
    'Wikipedia links (mg)': {'link': 'wikipedia_link_mg'},
    'Wikipedia links (my)': {'link': 'wikipedia_link_my'},
    'Wikipedia links (su)': {'link': 'wikipedia_link_su'},
    'Wikipedia links (qu)': {'link': 'wikipedia_link_qu'},
    'Wikipedia links (ba)': {'link': 'wikipedia_link_ba'},
    'Wikipedia links (ilo)': {'link': 'wikipedia_link_ilo'},
    'Wikipedia links (scn)': {'link': 'wikipedia_link_scn'},
    'Wikipedia links (an)': {'link': 'wikipedia_link_an'},
    'Wikipedia links (mzn)': {'link': 'wikipedia_link_mzn'},
    'Wikipedia links (lb)': {'link': 'wikipedia_link_lb'},
    'Wikipedia links (gu)': {'link': 'wikipedia_link_gu'},
    'Wikipedia links (pnb)': {'link': 'wikipedia_link_pnb'},
    'Wikipedia links (sco)': {'link': 'wikipedia_link_sco'},
    'Wikipedia links (eml)': {'link': 'wikipedia_link_eml'},
    'Wikipedia links (ga)': {'link': 'wikipedia_link_ga'},
    'Wikipedia links (br)': {'link': 'wikipedia_link_br'},
    'Wikipedia links (zh-yue)': {'link': 'wikipedia_link_zh_yue'},
    'Notre Dame': {'link': 'web-NotreDame'},
    'Wikipedia links (mr)': {'link': 'wikipedia_link_mr'},
    'Wikipedia links (new)': {'link': 'wikipedia_link_new'},
    'Wikipedia links (jv)': {'link': 'wikipedia_link_jv'},
    'Wikipedia links (af)': {'link': 'wikipedia_link_af'},
    'Wikipedia links (ia)': {'link': 'wikipedia_link_ia'},
    'Wikipedia links (ast)': {'link': 'wikipedia_link_ast'},
    'Wikipedia links (ml)': {'link': 'wikipedia_link_ml'},
    'Wikipedia links (bpy)': {'link': 'wikipedia_link_bpy'},
    'Wikipedia links (tl)': {'link': 'wikipedia_link_tl'},
    'Stanford': {'link': 'web-Stanford'},
    'Wikipedia links (sq)': {'link': 'wikipedia_link_sq'},
    'Wikipedia links (be-x-old)': {'link': 'wikipedia_link_be_x_old'},
    'Wikipedia links (ne)': {'link': 'wikipedia_link_ne'},
    'Wikipedia links (bn)': {'link': 'wikipedia_link_bn'},
    'Wikipedia links (te)': {'link': 'wikipedia_link_te'},
    'Wikipedia links (cy)': {'link': 'wikipedia_link_cy'},
    'Italian CNR': {'link': 'dimacs10-cnr-2000'},
    'Baidu related': {'link': 'zhishi-baidu-relatedpages'},
    'Wikipedia dynamic (simple)': {'link': 'link-dynamic-simplewiki'},
    'Wikipedia links (lmo)': {'link': 'wikipedia_link_lmo'},
    'Wikipedia links (lv)': {'link': 'wikipedia_link_lv'},
    'Wikipedia links (nn)': {'link': 'wikipedia_link_nn'},
    'Wikipedia links (la)': {'link': 'wikipedia_link_la'},
    'Wikipedia links (sa)': {'link': 'wikipedia_link_sa'},
    'Wikipedia links (uz)': {'link': 'wikipedia_link_uz'},
    'Wikipedia links (az)': {'link': 'wikipedia_link_az'},
    'Wikipedia links (zh-min-nan)': {'link': 'wikipedia_link_zh_min_nan'},
    'Wikipedia links (tt)': {'link': 'wikipedia_link_tt'},
    'Wikipedia links (mk)': {'link': 'wikipedia_link_mk'},
    'Wikipedia links (ka)': {'link': 'wikipedia_link_ka'},
    'Wikipedia links (simple)': {'link': 'wikipedia_link_simple'},
    'Wikipedia links (et)': {'link': 'wikipedia_link_et'},
    'Wikipedia links (bug)': {'link': 'wikipedia_link_bug'},
    'Wikipedia links (tg)': {'link': 'wikipedia_link_tg'},
    'Google hyperlinks': {'link': 'web-Google'},
    'Wikipedia links (el)': {'link': 'wikipedia_link_el'},
    'Wikipedia links (th)': {'link': 'wikipedia_link_th'},
    'Wikipedia links (lt)': {'link': 'wikipedia_link_lt'},
    'Wikipedia links (be)': {'link': 'wikipedia_link_be'},
    'Wikipedia links (gl)': {'link': 'wikipedia_link_gl'},
    'Wikipedia links (ur)': {'link': 'wikipedia_link_ur'},
    'Wikipedia links (ce)': {'link': 'wikipedia_link_ce'},
    'Wikipedia links (hr)': {'link': 'wikipedia_link_hr'},
    'Wikipedia links (sk)': {'link': 'wikipedia_link_sk'},
    'Wikipedia links (ta)': {'link': 'wikipedia_link_ta'},
    'Wikipedia links (hi)': {'link': 'wikipedia_link_hi'},

    'Wikipedia links (sl)': {'link': 'wikipedia_link_sl'},
    'Wikipedia links (eu)': {'link': 'wikipedia_link_eu'},
    'TREC WT10g': {'link': 'trec-wt10g'},
    'Wikipedia links (bg)': {'link': 'wikipedia_link_bg'},
    'Wikipedia links (da)': {'link': 'wikipedia_link_da'},
    'Wikipedia links (eo)': {'link': 'wikipedia_link_eo'},
    'Wikipedia links (bs)': {'link': 'wikipedia_link_bs'},
    'Wikipedia links (kk)': {'link': 'wikipedia_link_kk'},
    'Wikipedia links (he)': {'link': 'wikipedia_link_he'},
    'Wikipedia links (tr)': {'link': 'wikipedia_link_tr'},
    'Wikipedia links (fi)': {'link': 'wikipedia_link_fi'},
    'Indian domain': {'link': 'dimacs10-in-2004'},
    'Hudong internal': {'link': 'zhishi-hudong-internallink'},
    'European Union domain': {'link': 'dimacs10-eu-2005'},
    'Baidu internal': {'link': 'zhishi-baidu-internallink'},
    'Wikipedia links (cs)': {'link': 'wikipedia_link_cs'},
    'Wikipedia links (hy)': {'link': 'wikipedia_link_hy'},
    'Wikipedia links (no)': {'link': 'wikipedia_link_no'},
    'Wikipedia links (oc)': {'link': 'wikipedia_link_oc'},
    'Hudong related': {'link': 'zhishi-hudong-relatedpages'},
    'Wikipedia links (ms)': {'link': 'wikipedia_link_ms'},
    'Wikipedia links (ko)': {'link': 'wikipedia_link_ko'},
    'Wikipedia links (ro)': {'link': 'wikipedia_link_ro'},
    'Wikipedia links (id)': {'link': 'wikipedia_link_id'},
    'Wikipedia links (war)': {'link': 'wikipedia_link_war'},
    'Wikipedia links (ca)': {'link': 'wikipedia_link_ca'},
    'Wikipedia dynamic (nl)': {'link': 'link-dynamic-nlwiki'},
    'Wikipedia links (hu)': {'link': 'wikipedia_link_hu'},
    'Wikipedia links (es)': {'link': 'wikipedia_link_es'},
    'Wikipedia dynamic (pl)': {'link': 'link-dynamic-plwiki'},
    'Wikipedia links (vi)': {'link': 'wikipedia_link_vi'},
    'Wikipedia links (pt)': {'link': 'wikipedia_link_pt'},
    'Wikipedia links (uk)': {'link': 'wikipedia_link_uk'},
    'Wikipedia links (nl)': {'link': 'wikipedia_link_nl'},
    'Wikipedia dynamic (it)': {'link': 'link-dynamic-itwiki'},
    'Zhishi': {'link': 'zhishi-all'},
    'Wikipedia growth (en)': {'link': 'wikipedia-growth'},
    'Wikipedia dynamic (fr)': {'link': 'link-dynamic-frwiki'},
    'New York City': {'link': 'dimacs9-NY'},
    'San Francisco Bay Area': {'link': 'dimacs9-BAY'},
    'Colorado': {'link': 'dimacs9-COL'},
    'Pennsylvania': {'link': 'roadNet-PA'},
    'Texas': {'link': 'roadNet-TX'},
    'Florida': {'link': 'dimacs9-FLA'},
    'Northwest USA': {'link': 'dimacs9-NW'},
    'California': {'link': 'roadNet-CA'},
    'Northeast USA': {'link': 'dimacs9-NE'},
    'California and Nevada': {'link': 'dimacs9-CAL'},
    'Great Lakes': {'link': 'dimacs9-LKS'},
    'Eastern USA': {'link': 'dimacs9-E'},
    'Western USA': {'link': 'dimacs9-W'},
    'Central USA': {'link': 'dimacs9-CTR'},
    'Full USA': {'link': 'dimacs9-USA'},
    'vi.sualize.us user–tag': {'link': 'pics_ut'},
    'vi.sualize.us user–item': {'link': 'pics_ui'},
    'BibSonomy user–tag': {'link': 'bibsonomy-2ut'},
    'BibSonomy user–item': {'link': 'bibsonomy-2ui'},
    'CiteULike user–tag': {'link': 'citeulike-ut'},
    'CiteULike user–item': {'link': 'citeulike-ui'},
    'Prosper loans': {'link': 'prosper-loans'},
    'Twitter user–tag': {'link': 'munmun_twitterex_ut'},
    'Last.fm bands': {'link': 'lastfm_band'},
    'Last.fm songs': {'link': 'lastfm_song'},
    'Edinburgh Associative Thesaurus': {'link': 'eat'},
    'WordNet': {'link': 'wordnet-words'},
    'Yahoo advertisers': {'link': 'lasagne-yahoo'},
    'Amazon (MDS)': {'link': 'com-amazon'},
    'Amazon (TWEB, 0601)': {'link': 'amazon0601'},
    'DBpedia': {'link': 'dbpedia-all'},
    'Actor collaborations': {'link': 'actor-collaboration'},
    'WikiSigned': {'link': 'wikisigned-k2'},
    'MathOverflow': {'link': 'sx-mathoverflow'},
    'Ask Ubuntu': {'link': 'sx-askubuntu'},
    'Super User': {'link': 'sx-superuser'},
    'Wikipedia conflict': {'link': 'wikiconflict'},
    'Stack Overflow': {'link': 'stackexchange-stackoverflow'},
    'Epinions': {'link': 'epinions-rating'},
    'Gowalla': {'link': 'loc-gowalla_edges'},
    'Twitter (ICWSM)': {'link': 'munmun_twitter_social'},
    'Facebook (WOSN)': {'link': 'facebook-wosn-links'},
    'Livemocha': {'link': 'livemocha'},
    'Dogster households': {'link': 'petster-dog-household'},
    'Youtube friendships': {'link': 'com-youtube'},
    'Hyves': {'link': 'hyves'},
    'Digg friends': {'link': 'digg-friends'},
    'Youtube links': {'link': 'youtube-links'},
    'Catster friends': {'link': 'petster-cat-friend'},
    'Flixster': {'link': 'flixster'},
    'Dogster friends': {'link': 'petster-dog-friend'},
    'Higgs': {'link': 'higgs-twitter-social'},
    'Flickr links': {'link': 'flickr-links'},
    'YouTube': {'link': 'youtube-u-growth'},
    'Libimseti.cz': {'link': 'libimseti'},
    'Pokec': {'link': 'soc-pokec-relationships'},
    'LiveJournal links': {'link': 'livejournal-links'},
    'CiaoDVD review ratings': {'link': 'librec-ciaodvd-review_ratings'},
    'MovieLens 1M': {'link': 'movielens-1m'},
    'Jester 150': {'link': 'jester2'},
    'Jester 100': {'link': 'jester1'},
    'Digg votes': {'link': 'digg-votes'},
    'Amazon ratings': {'link': 'amazon-ratings'},
    'MovieLens 10M': {'link': 'movielens-10m_rating'},
    'NIPS full papers': {'link': 'bag-nips'},
    'Reuters-21578': {'link': 'gottron-reuters'},
    'Wikipedia words (en)': {'link': 'gottron-excellent'},
    'Enron words': {'link': 'bag-enron'},
    'WebUni Magdeburg': {'link': 'webuni'}

}

#####################

konect_tiny_only = ['soc_libimseti', 'web_stanford', 'road_colorado', 'soc_catster_dogster', 'soc_youtube_friendships',
                    'road_texas', 'soc_pokec', 'road_california', 'web_baidu_internal', 'rating_epinions']
syn_tiny_only = ["syn_rmat_18_32", "syn_ru_18_32", "syn_rmat_20_32", "syn_ru_20_32"]

#####################

konect_small_only = ['soc_orkut', 'web_wikipedia_links_fr', 'web_wikipedia_links_ru', 'rating_amazon_ratings',
                     'road_eastern_usa', 'soc_livejournal', 'soc_livejournal_links', 'road_western_usa', 'web_zhishi']
syn_small_only = ["syn_rmat_22_32", "syn_ru_22_32"]

#####################

konect_medium_only = ['web_wikipedia_links_en', 'road_central_usa', 'web_dbpedia_links', 'web_uk_domain_2002',
                      'rating_yahoo_songs']
syn_medium_only = ["syn_rmat_24_32", "syn_ru_24_32"]

#####################

konect_large_only = ['road_full_usa', 'web_web_trackers', 'soc_twitter_www', 'soc_friendster']
syn_large_only = ["syn_rmat_25_32", "syn_ru_25_32"]

#####################

konect_tiny_small = konect_tiny_only + konect_small_only
syn_tiny_small = syn_tiny_only + syn_small_only

konect_tiny_small_medium = konect_tiny_only + konect_small_only + konect_medium_only
syn_tiny_small_medium = syn_tiny_only + syn_small_only + syn_medium_only

#####################

konect_rating_tiny = ['web_stanford', 'soc_youtube_friendships', 'road_texas', 'rating_epinions']
konect_rating_small = ['soc_livejournal_links', 'road_western_usa', 'web_zhishi', 'rating_amazon_ratings']
konect_rating_medium = ['road_central_usa', 'web_uk_domain_2002', 'rating_yahoo_songs']
#konect_rating_large = ['soc_twitter_www', 'road_full_usa', 'web_web_trackers']

konect_rating_large = ['road_full_usa', 'web_web_trackers']

syn_rating_tiny = ["syn_rmat_18_32", "syn_ru_18_32"]
syn_rating_small = ["syn_rmat_22_32", "syn_ru_22_32"]
syn_rating_medium = ["syn_rmat_24_32", "syn_ru_24_32"]
syn_rating_large = ["syn_rmat_25_32", "syn_ru_25_32"]


konect_rating_fast = konect_rating_tiny + konect_rating_small
syn_rating_fast = syn_rating_tiny + syn_rating_small

#####################

konect_rating_avg = konect_rating_tiny + konect_rating_small + konect_rating_medium + konect_rating_large
syn_rating_avg = syn_rating_tiny + syn_rating_small

#####################
# IGNORE MEDIUM AND LARGE

konect_rating_full = konect_rating_tiny + konect_rating_small + konect_rating_medium + konect_rating_large
syn_rating_full = syn_rating_tiny + syn_rating_small

#####################

syn_scaling = ["syn_rmat_18_32", "syn_rmat_19_32", "syn_rmat_20_32", "syn_rmat_21_32", "syn_rmat_22_32",
               "syn_rmat_23_32"]
konect_scaling = []

#####################

apps_and_graphs_ingore = {"sssp": [],
                          "bfs": []}

konect_fastest = ['soc_catster_dogster', 'road_texas']
syn_fastest = ["syn_rmat_18_32", "syn_ru_18_32"]

#may be temporarirly
syn_great = []


gpu_format_ml = ["Wikibooks edits (de)",
"Wikipedia edits (bar)",
"Wikipedia edits (ku)",
"Wikipedia edits (qu)",
"Wiktionary edits (ar)",
"Wikipedia edits (ht)",
"Wikipedia edits (bpy)",
"Wiktionary edits (id)",
"Wiktionary edits (ca)",
"Wikiversity edits (en)",
"Wiktionary edits (lt)",
"Wikipedia edits (be-x-old)",
"Wikipedia edits (te)",
"Wikipedia edits (bs)",
"Wiktionary edits (io)",
"Wikipedia edits (lt)",
"Wikipedia edits (th)",
"Wikipedia edits (eu)",
"Wikipedia edits (war)",
"Wikipedia edits (da)",
"Wikipedia edits (fi)",
"Wikipedia edits (ca)",
"arXiv hep-ph",
"Wikipedia talk (ru)",
"Wikipedia talk (fr)",
"Wikipedia talk (en)",
"Reality Mining",
"Wikipedia links (su)",
"Wikipedia links (scn)",
"Wikipedia links (mzn)",
"Wikipedia links (sco)",
"Wikipedia links (eml)",
"Wikipedia links (new)",
"Wikipedia links (ia)",
"Wikipedia links (ml)",
"Wikipedia links (te)",
"Wikipedia links (la)",
"Wikipedia links (uz)",
"Wikipedia links (eu)",
"Wikipedia links (fi)",
"European Union domain",
"Colorado",
"California",
"Great Lakes",
"CiteULike user–item",
"DBpedia",
"Ask Ubuntu",
"Hyves",
"LiveJournal links",
"CiaoDVD review ratings",
"Jester 150",
"Jester 100",
"Reuters-21578",
"Enron words",
"WebUni Magdeburg"]

gpu_format_ml_pr = ["Wikipedia edits (nap)",
"Wikipedia edits (ne)",
"Wikipedia edits (bar)",
"Wikipedia edits (qu)",
"Wikipedia edits (new)",
"Wiktionary edits (th)",
"Wikipedia edits (ast)",
"Wikiquote edits (zh)",
"Wikipedia edits (mr)",
"Wiktionary edits (sh)",
"Wikipedia edits (uz)",
"Wiktionary edits (pt)",
"Wiktionary edits (io)",
"Wikipedia edits (ms)",
"Wikipedia edits (hr)",
"Wikipedia edits (el)",
"Wikipedia edits (ceb)",
"Wikipedia edits (pt)",
"Wikipedia edits (zh)",
"Wiktionary edits (en)",
"US patents",
"Linux kernel mailing list replies",
"Enron",
"Wikipedia threads (de)",
"Wikipedia talk (es)",
"Reality Mining",
"Wikipedia links (yi)",
"Wikipedia links (cv)",
"Wikipedia links (yo)",
"Wikipedia links (my)",
"Wikipedia links (su)",
"Wikipedia links (pnb)",
"Wikipedia links (eml)",
"Wikipedia links (lv)",
"Wikipedia links (mk)",
"Google hyperlinks",
"Wikipedia links (sk)",
"Wikipedia links (bg)",
"Wikipedia links (da)",
"Wikipedia links (he)",
"Wikipedia links (tr)",
"European Union domain",
"Hudong related",
"Wikipedia links (id)",
"California",
"Northeast USA",
"CiteULike user–item",
"Yahoo advertisers",
"Actor collaborations",
"Youtube friendships",
"Youtube links",
"CiaoDVD review ratings",
"Jester 150",
"Enron words",
"WebUni Magdeburg"]

cpu_format_ml = ["CiteSeer",
"Wikinews edits (es)",
"Wikipedia edits (nap)",
"Wiktionary edits (li)",
"Wikipedia edits (als)",
"Wikipedia edits (io)",
"Wiktionary edits (ja)",
"Wikipedia edits (is)",
"Wikipedia edits (tl)",
"Wikiversity edits (en)",
"Wikipedia edits (br)",
"Wikipedia edits (zh-min-nan)",
"Wikipedia edits (tt)",
"Wiktionary edits (io)",
"Wikiquote edits (de)",
"Wikipedia edits (hr)",
"Wiktionary edits (es)",
"Wikipedia edits (hy)",
"Wikipedia edits (hu)",
"Wikipedia edits (fa)",
"Wikipedia edits (sv)",
"Wikipedia edits (zh)",
"arXiv hep-ph",
"Wikipedia talk (en)",
"Wikipedia categories (en)",
"CiteULike tag–item",
"Wikipedia links (ps)",
"Wikipedia links (io)",
"Wikipedia links (my)",
"Wikipedia links (lb)",
"Wikipedia links (br)",
"Wikipedia links (ia)",
"Wikipedia links (ml)",
"Baidu related",
"Wikipedia dynamic (simple)",
"Wikipedia links (lv)",
"Wikipedia links (uz)",
"Wikipedia links (tt)",
"Wikipedia links (da)",
"Wikipedia links (eo)",
"Wikipedia links (no)",
"Wikipedia links (oc)",
"Wikipedia links (ms)",
"Zhishi",
"New York City",
"Great Lakes",
"BibSonomy user–tag",
"Last.fm bands",
"Amazon (TWEB, 0601)",
"Epinions",
"Gowalla",
"Twitter (ICWSM)",
"Youtube friendships",
"Hyves",
"Jester 100",
"Enron words"]

gpu_format_ml_cc = [
"Wikibooks edits (de)",
"Wikipedia edits (kn)",
"Wikiquote edits (he)",
"Wikipedia edits (tg)",
"Wiktionary edits (ro)",
"Wikipedia edits (zh-yue)",
"Wiktionary edits (no)",
"Wiktionary edits (bg)",
"Wikipedia edits (tl)",
"Wikipedia edits (mr)",
"Wikiversity edits (en)",
"Wiktionary edits (ta)",
"Wikipedia edits (bs)",
"Wikibooks edits (en)",
"Wiktionary edits (nl)",
"Wikipedia edits (ms)",
"Wiktionary edits (zh)",
"Wiktionary edits (pl)",
"Wikipedia edits (bg)",
"Wikipedia edits (da)",
"Wiktionary edits (ru)",
"Wikipedia edits (ko)",
"Wikipedia edits (fa)",
"Facebook",
"Linux kernel mailing list replies",
"Wikipedia threads (de)",
"Wikipedia links (als)",
"Wikipedia links (roa-tara)",
"Wikipedia links (lb)",
"Wikipedia links (gu)",
"Wikipedia links (eml)",
"Wikipedia links (zh-yue)",
"Wikipedia links (ka)",
"Wikipedia links (simple)",
"Google hyperlinks",
"Wikipedia links (el)",
"Wikipedia links (hr)",
"Wikipedia links (da)",
"Wikipedia links (fi)",
"European Union domain",
"Colorado",
"California",
"Central USA",
"vi.sualize.us user–tag",
"BibSonomy user–tag",
"Twitter user–tag",
"WordNet",
"Amazon (TWEB, 0601)",
"Actor collaborations",
"MathOverflow",
"Super User",
"Livemocha",
"Youtube friendships",
"Digg friends",
"Pokec",
"MovieLens 10M"]

gpu_format_ml_sssp= [
"CiteSeer",
"Wikipedia edits (su)",
"Wikipedia edits (ia)",
"Wikiquote edits (es)",
"Wikipedia edits (new)",
"Wikinews edits (it)",
"Wiktionary edits (no)",
"Wikiquote edits (zh)",
"Wikipedia edits (af)",
"Wikipedia edits (min)",
"Wiktionary edits (lt)",
"Wikipedia edits (lb)",
"Wikivoyage edits (en)",
"Wikipedia edits (bs)",
"Wikibooks edits (en)",
"Wikipedia edits (be)",
"Wikiquote edits (de)",
"Wikipedia edits (hi)",
"Wikipedia edits (ka)",
"Wikinews edits (en)",
"Wikiquote edits (fr)",
"Wikipedia edits (cs)",
"Wikipedia edits (tr)",
"Wikipedia edits (hu)",
"Wikipedia edits (pt)",
"Wikipedia edits (zh)",
"vi.sualize.us tag–item",
"BibSonomy tag–item",
"CiteULike tag–item",
"Reality Mining",
"Wikipedia links (yi)",
"Wikipedia links (bar)",
"Wikipedia links (cv)",
"Wikipedia links (ky)",
"Wikipedia links (su)",
"Wikipedia links (mzn)",
"Italian CNR",
"Wikipedia links (da)",
"Wikipedia links (kk)",
"Wikipedia links (fi)",
"European Union domain",
"Wikipedia links (ro)",
"Wikipedia links (nl)",
"Pennsylvania",
"vi.sualize.us user–item",
"BibSonomy user–item",
"CiteULike user–item",
"Amazon (TWEB, 0601)",
"WikiSigned",
"Youtube friendships",
"Hyves",
"Dogster friends",
"Pokec",
"MovieLens 10M",
"Reuters-21578",
"Enron words",
"WebUni Magdeburg"]

cpu_format_ml_pr = [
"IMDB",
"Wikinews edits (es)",
"Wikipedia edits (vec)",
"Wikiversity edits (fr)",
"Wikipedia edits (qu)",
"Wiktionary edits (fa)",
"Wikinews edits (fr)",
"Wikipedia edits (ga)",
"Wikivoyage edits (de)",
"Wikipedia edits (mr)",
"Wiktionary edits (ta)",
"Wiktionary edits (pt)",
"Wikipedia edits (ta)",
"Wikipedia edits (nn)",
"Wikipedia edits (la)",
"Wiktionary edits (fi)",
"Wiktionary edits (es)",
"Wikipedia edits (eu)",
"Wikipedia edits (war)",
"Wikipedia edits (hu)",
"Wikipedia edits (ja)",
"Wiktionary edits (en)",
"Wikipedia edits (ru)",
"Wikipedia threads (de)",
"Wikipedia talk (it)",
"Wikipedia links (yi)",
"Wikipedia links (als)",
"Wikipedia links (ku)",
"Wikipedia links (is)",
"Wikipedia links (an)",
"Wikipedia links (lb)",
"Wikipedia links (new)",
"Wikipedia links (ast)",
"Italian CNR",
"Baidu related",
"Wikipedia links (tt)",
"Google hyperlinks",
"Wikipedia links (bg)",
"Wikipedia links (kk)",
"Baidu internal",
"Wikipedia links (cs)",
"Wikipedia links (oc)",
"Wikipedia links (war)",
"Wikipedia links (es)",
"Colorado",
"Northwest USA",
"Great Lakes",
"CiteULike user–item",
"Prosper loans",
"Yahoo advertisers",
"Actor collaborations",
"Hyves",
"Dogster friends",
"Digg votes",
"Reuters-21578",
"Wikipedia words (en)",
"Enron words"
]

cpu_format_ml_cc =[
    "Teams",
"Actor movies",
"Wiktionary edits (sa)",
"Wikiversity edits (fr)",
"Wikipedia edits (ku)",
"Wikiquote edits (it)",
"Wikiquote edits (he)",
"Wikipedia edits (new)",
"Wiktionary edits (id)",
"Wiktionary edits (no)",
"Wiktionary edits (bg)",
"Wiktionary edits (ca)",
"Wikipedia edits (min)",
"Wikipedia edits (ce)",
"Wikipedia edits (uz)",
"Wikipedia edits (la)",
"Wikipedia edits (vo)",
"Wikipedia edits (sl)",
"Wikipedia edits (fi)",
"Wikipedia edits (ar)",
"Wiktionary edits (fr)",
"Wikipedia edits (zh)",
"Wiktionary edits (en)",
"DBLP co-authorship",
"arXiv hep-ph",
"Wikipedia talk (vi)",
"Wikipedia talk (ar)",
"Wikipedia talk (ru)",
"Skitter",
"Wikipedia links (vo)",
"Wikipedia links (cv)",
"Wikipedia links (nap)",
"Wikipedia links (fy)",
"Wikipedia links (ba)",
"Wikipedia links (ilo)",
"Wikipedia links (lv)",
"Wikipedia links (la)",
"Wikipedia links (simple)",
"Wikipedia links (ta)",
"Wikipedia links (sl)",
"Wikipedia links (eu)",
"TREC WT10g",
"Hudong related",
"Wikipedia links (ms)",
"Wikipedia links (ro)",
"Wikipedia links (id)",
"Wikipedia dynamic (nl)",
"Wikipedia dynamic (pl)",
"Zhishi",
"Colorado",
"Texas",
"vi.sualize.us user–item",
"Prosper loans",
"Gowalla",
"Dogster households",
"WebUni Magdeburg"
]

cpu_format_ml_sssp = [
"Actor movies",
"Wikipedia edits (bar)",
"Wikipedia edits (ku)",
"Wikipedia edits (ht)",
"Wikipedia edits (ba)",
"Wikipedia edits (arz)",
"Wikinews edits (fr)",
"Wikipedia edits (mg)",
"Wikipedia edits (tg)",
"Wikipedia edits (zh-yue)",
"Wikipedia edits (an)",
"Wikipedia edits (sq)",
"Wikipedia edits (br)",
"Wikipedia edits (be-x-old)",
"Wikipedia edits (tt)",
"Wikivoyage edits (en)",
"Wikipedia edits (be)",
"Wiktionary edits (io)",
"Wikipedia edits (lv)",
"Wikipedia edits (ur)",
"Wikipedia edits (mk)",
"Wikipedia edits (ka)",
"Wiktionary edits (ko)",
"Wiktionary edits (zh)",
"Wikipedia edits (cs)",
"Wikipedia edits (he)",
"Wikipedia edits (uk)",
"Wiktionary edits (mg)",
"Wikipedia edits (nl)",
"Enron",
"Wikipedia threads (de)",
"Wikipedia talk (it)",
"Wikipedia talk (de)",
"vi.sualize.us tag–item",
"TV Tropes",
"Wikipedia links (mg)",
"Wikipedia links (ba)",
"Wikipedia links (tl)",
"Wikipedia links (ne)",
"Wikipedia links (lmo)",
"Wikipedia links (uz)",
"Wikipedia links (th)",
"Wikipedia links (lt)",
"Wikipedia links (bg)",
"European Union domain",
"Hudong related",
"Wikipedia links (ms)",
"Wikipedia links (war)",
"Full USA",
"WordNet",
"Epinions",
"Dogster friends",
"Higgs",
"YouTube",
"MovieLens 10M",
"Wikipedia words (en)"
]

gpu_bfs_format_label = {0:"csr", 1:"vcsr", 2:"el"}

mc_bfs_format_label = {0:"csr", 1:"csr_vg", 2:"vcsr", 3: "el", 4: "el_csr_based"}